### ISSUE TITLE
Things to address before 1.0.0 release

### ISSUE THREAD

**Issue by kategengler** [kategengler/ember-cli-code-coverage#152]
- [x] Move the test figures from app/addon to a dedicated addon for testing. Be sure to remove the treeFor hook after doing so. 

- [ ] Should coverage for addons be testing the % coverage of the dummy app or of the addon itself? I would think the later. (But not sure if this ever behaved this way).

- [x] I think we might want to bring back the try/catch around the require here https://github.com/kategengler/ember-cli-code-coverage/pull/145/files#diff-94eab975fb48e219fc130d82e21457acR6 so that if it does happen, we don't break anything. It was put in place because apparently people have some unused files in their apps that never get used and may be completely broken. Is this test https://github.com/kategengler/ember-cli-code-coverage/blob/master/tests/unit/handle-modules-throwing-on-import-test.js still testing the desired behavior? __This has been handled in #153__

### TODO
 - [ ] Manually test coverage-merge
 - [ ] Manually test that files that are not required contribute to coverage % (a completely not tested or even used file lowers coverage %)
 - [ ] Manually test that Addon files do not contribute to coverage % of app
 - [ ] Manually test out using .istanbul.yml for configuration. Do we support all options? What if they conflict with our config? (If we don't support this for 1.0 it can be put off)
 - [ ] Audit README for correctness
 - [ ] Upgrade ember-cli to latest stable

**Comment by apellerano-pw** [comment]
I've been following the 1.0.0 release closely because I want dat speed improvement, just wanted to share a benchmark (in seconds) from the 1.0.0-beta.4 build

```
COVERAGE=true
0.4.1:  232.80s
1.0.0-beta.4: 144.23s
```

Looks promising! :tada:

**Comment by rwwagner90** [comment]
@kategengler what is required before the 1.0 release? I think we should go ahead and release a 1.0, as the currently released versions do not work in a lot of cases, but the betas do, so I think we need to have the latest version working. What do you think?

**Comment by kategengler** [comment]
@rwwagner90 That was what was intended this issue was intended to be a list of -- those list of manual tests + auditing the README. At this point, I'd also say we have to update `ember-cli` to a more recent, non-beta version. 

I wouldn't require it for 1.0, but probably shortly after we should upgrade to the latest `babel-plugin-istanbul`, if that's not something we

**Comment by rwwagner90** [comment]
@kategengler I can update ember-cli and see about babel-plugin-istanbul.

**Comment by rwjblue** [comment]
I think we've done most of this (and if not, folks should report specific issues), so I'm closing as 1.0.0 is released.
